# Vector creation 

In this notebook we will see how can we creat various type of vectors using numpy module of python

## Import numpy module

In [3]:
import numpy as np

## Lists and tupples

If your vector is already defined in lists or tupples data type we can create vector in numpy using them.

In [4]:
#List
v_l = [1,0,0]
v_n = np.array(v_l)
v_n

array([1, 0, 0])

In [5]:
#tupple
v_t = [1,0,0]
v_n = np.array(v_t)
v_n

array([1, 0, 0])

## Shape of vector
The shape of vector is nothing but the dimensions of the vector

In [6]:
#shape
v_n.shape

(3,)

In [7]:
#reshape the vector to a new dimension
v_n = v_n.reshape((1,3)) #(3,1) is the new dimension
v_n.shape

(1, 3)

## Ones and zeros vectors
we can create vectors like containing only zeros or ones directly

In [8]:
#zeros vector
v_0 = np.zeros((1,3))
v_0

array([[0., 0., 0.]])

In [9]:
#ones vector
v_1 = np.ones((1,3))
v_1

array([[1., 1., 1.]])

## Row vector
A vector which has only one row is row vector. Example $$ v_r = \begin{bmatrix} x_1 & y_1 \end{bmatrix} $$ the shape of above vector is (1,2)

In [17]:
#Now lets create a row vector
a_r = [20, 30]
v_r = np.array(a_r)
v_r = v_r.reshape((1,2))
v_r

array([[20, 30]])

In [18]:
#the shape of above vector is given by
v_r.shape

(1, 2)

## Column vector
A vector which has only one column is column vector. Example $$ v_c = \begin{bmatrix} x_1 \\ y_1 \end{bmatrix} $$ the shape of above vector is (2,1)

In [21]:
#Now lets create a column vector
a_c = [[20], [30]]
v_c = np.array(a_c)
v_c = v_c.reshape((2,1))
v_c

array([[20],
       [30]])

In [22]:
#the shape of above vector is given by 
v_c.shape

(2, 1)

## Null vector 
A vector which has all zeros as the elements is the null vector. Example $$ v_{n1} = \begin{bmatrix} 0 \\ 0 \end{bmatrix}$$ $$v_{n2} = \begin{bmatrix} 0 & 0 \end{bmatrix}$$

In [23]:
#create null row vector
v_nr = np.zeros((1,2))
v_nr

array([[0., 0.]])

In [24]:
#creat null column vector
v_nc = np.zeros((2,1))
v_nc

array([[0.],
       [0.]])

## to be continued..