# Vector Operations
In this we will discuss different vector operations like additions, subtractions, dot product, and cross products <br>

Before let's define two column vectors $a_1$ and $a_2$ on which we will perform bunch of operations
$$ a_1 = \begin{bmatrix} x_1 \\ y_1 \end{bmatrix} $$ $$ \\b_1 = \begin{bmatrix} x_2 \\ y_2 \end{bmatrix} $$

In [1]:
#import numpy module
import numpy as np

In [2]:
#now lets see an example
a_1 = [[1],[2]]
a_1 = np.array(a_1)
a_1 = a_1.reshape((2,1))
a_1

array([[1],
       [2]])

In [3]:
a_2 = [[3],[4]]
a_2 = np.array(a_2)
a_2 = a_2.reshape((2,1))
a_2

array([[3],
       [4]])

## Addition
Now the addition of two vectors $$ a = a_1 + a_2 $$ which can be written as $$ a = \begin{bmatrix} x_1 \\ y_1 \end{bmatrix} + \begin{bmatrix} x_2 \\ y_2 \end{bmatrix} $$ which can be further evaluated as $$ a = \begin{bmatrix} x_1 + x_2 \\ y_1 + y_2 \end{bmatrix} $$

In [4]:
# Now in case of numpy arrays 
# addition is done by simply adding the two vectors 
a = a_1 + a_2
a

array([[4],
       [6]])

## Subtraction
Subtraction is given by the difference between two vectors $$ a = a_1 - a_2 $$ Which can be written as $$ a = \begin{bmatrix} x_1 \\ y_1 \end{bmatrix} -  \begin{bmatrix} x_2 \\ y_2 \end{bmatrix} $$ which can be further evaluateed as $$ a = \begin{bmatrix} x_1 - x_2 \\ y_1 - y_2 \end{bmatrix} $$

In [5]:
# Now in case of numpy arrays
# subtraction is done by simply takeing the difference between as shown in the above equation
s = a_1 - a_2
s

array([[-2],
       [-2]])

## Element-wise multiplication
This is just you are simply multiplying the element by element $$ a = a_1 * a_2 $$ which can be written as $$ a = \begin{bmatrix} x_1 \\ y_1 \end{bmatrix} * \begin{bmatrix} x_2 \\ y_2 \end{bmatrix} $$ which can be further evaluated as $$ a = \begin{bmatrix} x_1* x_2 \\ y_1*y_2 \end{bmatrix} $$

In [6]:
##Now we can do it in multiple ways
#without complicating things we can do it in the same way as given in the above expression
m = a_1*a_2
m

array([[3],
       [8]])

## Traspose of vector
The traspose of a vector changes in such a way that if it is column vector it becomes row vector and vise versa
and it is represented by $a_1^T$ if $$ a_1 = \begin{bmatrix} x_1 \\ y_1 \end{bmatrix} $$ now traspose of $a_1$ is given by $$ a_1^T = \begin{bmatrix} x_1 & y_1 \end{bmatrix} $$

In [7]:
#Using numpy we can get transpose by just a_1.T
#Now we have a_1 has a column vector 
#a_1.T gives a row vector
a_1.T

array([[1, 2]])

## Unit vector
Unit vector is the vector with unit magnitude and finite direction. We can define a unit vector corresponding to each vector which is given as follows $$ \hat a_1 = \frac{a_1}{|a_1|} $$ where $|a_1|$ is the magnitude the vector given $$ |a_1| = \sqrt(a_1^2+a_2^2) $$

In [10]:
#magnitude of the vector
a_m1 = np.linalg.norm(a_1)
#Unit vector in the direction of a_1 
a_u1 = a_1/a_m1
a_u1

array([[0.4472136 ],
       [0.89442719]])

In [12]:
np.linalg.norm(a_u1)

0.9999999999999999

## Dot product
If a vector is operated by dot product on the another vector it returns a scalar. It has the following form $$ a = a_1 * a_2^T $$ which can be written as $$ a = \begin{bmatrix} x_1 & y_1 \end{bmatrix} \begin{bmatrix} x_2 \\ y_2 \end{bmatrix} $$ after evaluating it returns a scalar $$ a = x_1*x_2  + y_1*y_2 $$

In [13]:
#Using numpy np.dot we can do this
a = np.dot(a_1,a_2.T)
a

array([[3, 4],
       [6, 8]])

## Cross product
If a vector is operated by cross product on the another vector it returns a vector. It has the following form $$ a = a_1 X a_2 $$
which can be written as $$ a = \begin{bmatrix} x_1 & y_1 & z_1 \end{bmatrix} X \begin{bmatrix} x_2 & y_2 & z_2\end{bmatrix} $$ Its worth noting that we extended our vector space to 3 dimensional by adding z direction as cross product is not defined in two dimensional space. After evaluating the above expression it returns a vector of form $$ a =  \begin{bmatrix} (y_2 z_3 - y_3z_2) & -(x_2z_3 -x_3z_2) & (x_2y_3-y_2x_3) \end{bmatrix} $$

In [14]:
#Now lets add the third dimesion as zero to our vectors a_1 and a_2
a_1_3d = np.concatenate([a_1,np.array([0]).reshape(1,1)],axis=0)
print("vector a_1 in 3d space \n {}".format(a_1_3d))
a_2_3d = np.concatenate([a_2,np.array([0]).reshape(1,1)],axis=0)
print("vector a_2 in 3d space \n {}".format(a_2_3d))

vector a_1 in 3d space 
 [[1]
 [2]
 [0]]
vector a_2 in 3d space 
 [[3]
 [4]
 [0]]


In [15]:
#Using numpy np.cross we can do this
a = np.cross(a_1.T,a_2.T)
a

array([-2])

In our next notebooks we will go ahead and explore dot and cross products in detail and their physical meaning and so on.

## Thank you..!